# conf.d/services.yaml
processes:
  - name: web-server-1
    group: web
    command: "while true; do { echo -e 'HTTP/1.1 200 OK\\r\\n\\r\\nHello from web-server-1'; } | nc -l -p 8080; done"
    workdir: "/tmp"
    enabled: true
    port: 8080
    stop_timeout_sec: 15
    depends_on:
      - api-server-1

  - name: api-server-1
    group: api
    command: "while true; do { echo -e 'HTTP/1.1 200 OK\\r\\n\\r\\nHello from api-server-2'; } | nc -l -p 8081; done"
    workdir: "/tmp"
    enabled: true
    port: 8081
    environment:
      API_KEY: "your-secret-key"
      GIN_MODE: "release"
