# GitHub Actions 工作流名称
name: Release Procmate Binary

# 工作流触发条件
on:
  push:
    # 只有当推送的是一个 tag 时，才触发此工作流
    tags:
      - 'v*' # 匹配所有以 'v' 开头的 tag, 例如 v1.0, v0.1.0

# 工作流包含的任务
jobs:
  # 定义一个名为 build-and-release 的任务
  build-and-release:
    # 指定任务运行的虚拟环境，使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest

    # VVVV 新增的权限声明 VVVV
    # 为此任务授予写入仓库内容的权限，这是创建 Release 所必需的
    permissions:
      contents: write
    # ^^^^ 新增的权限声明 ^^^^

    # 定义此任务的执行步骤
    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：设置 Go 语言环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 第三步：运行 GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
